# Generated by Django 5.2.7 on 2025-11-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='date_subimtted',
            new_name='date_submitted',
        ),
    ]
