# Generated by Django 5.2.7 on 2025-12-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_rename_date_subimtted_issue_date_submitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('credit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('OPTIONAL', 'Optional')], max_length=10)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='modules', to='itreporting.course')),
                ('students', models.ManyToManyField(blank=True, related_name='registered_modules', to='itreporting.student')),
            ],
        ),
    ]
