# Generated by Django 5.2.7 on 2025-12-24 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_remove_student_user_student_profile_and_more'),
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.profile'),
            preserve_default=False,
        ),
    ]
